---
- name: Show last 10 real soft lockups
  hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_python_interpreter: auto_silent

  tasks:
    - name: Find last 10 real kernel soft lockups
      ansible.builtin.shell: |
        awk '$5 == "kernel:" &&
             index($0, "watchdog: BUG: soft lockup") {
               print
             }' \
          $(ls -tr /var/log/messages* 2>/dev/null) \
          2>/dev/null | tail -10
      register: soft_lockups
      changed_when: false
      failed_when: false

    - name: Soft lockup status
      ansible.builtin.debug:
        msg: "PASS | No soft lockups found"
      when: soft_lockups.stdout_lines | length == 0

    - name: Soft lockup warning
      ansible.builtin.debug:
        msg: "WARNING | {{ soft_lockups.stdout_lines | length }} soft lockup(s) found"
      when: soft_lockups.stdout_lines | length > 0

    - name: Soft lockup
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ soft_lockups.stdout_lines }}"
      loop_control:
        label: "{{ inventory_hostname }}"
      when: soft_lockups.stdout_lines | length > 0
