---
- name: Show Ansible configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: Display active Ansible configuration
      ansible.builtin.command:
        cmd: ansible-config dump --only-changed
      delegate_to: localhost
      run_once: true
      register: ansible_config
      changed_when: false

    - name: Show configuration
      ansible.builtin.debug:
        var: ansible_config.stdout_lines
      run_once: true