---
- name: Check open-vm-tools
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check open-vm-tools package
      ansible.builtin.command:
        cmd: rpm -q open-vm-tools
      register: vmtools_package
      changed_when: false
      failed_when: false

    - name: Check vmtoolsd service
      ansible.builtin.command:
        cmd: systemctl is-active vmtoolsd
      register: vmtools_service
      changed_when: false
      failed_when: false

    - name: Display VMware Tools status
      ansible.builtin.debug:
        msg: |
          {{ inventory_hostname }}
          ----------------------------------------
          Package: {{ vmtools_package.stdout }}
          Service: {{ vmtools_service.stdout }}
